name: human-dev
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - pandas
      - numpy
      - scikit-learn
      - matplotlib
      - seaborn
      - jupyterlab
      - ipykernel
      - dagster
      - dagster-webserver
      - plotly

